//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuizManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int QuizID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<bool> wasAnsweredCorrectly { get; set; }
        public int HistoryID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
